export default [
  {
    id: 1,
    title: "Life Lessons with Katie Zaferes",
    description: "Interested in blablabla",
    price: 136,
    coverImg: "katie-zaferes.png",
    stats: {
      rating: "5.0",
      reviewCount: 6,
    },
    country: "USA",
    location: "Online",
    openSpots: 0,
  },
  {
    id: 2,
    title: "Learn Wedding Photografer",
    description: "Interested in blablabla",
    price: 126,
    coverImg: "wedding-photography 1.png",
    stats: {
      rating: "5.0",
      reviewCount: 30,
    },
    country: "America",
    location: "Online",
    openSpots: 26,
  },
  {
    id: 3,
    title: "Group Mountain Biking",
    description: "Biking",
    price: 136,
    coverImg: "mountain-bike 1.png",
    stats: {
      rating: "4.8",
      reviewCount: 2,
    },
    country: "Mexico",
    location: "Offline",
    openSpots: 50,
  },
  {
    id: 4,
    title: "Learn Wedding Photografer",
    description: "Interested in blablabla",
    price: 126,
    coverImg: "wedding-photography 1.png",
    stats: {
      rating: "5.0",
      reviewCount: 30,
    },
    country: "America",
    openSpots: 26,
  },
  {
    id: 5,
    title: "Group Mountain Biking",
    description: "Biking",
    price: 136,
    coverImg: "mountain-bike 1.png",
    stats: {
      rating: "4.8",
      reviewCount: 2,
    },
    country: "Mexico",
    openSpots: 50,
  },
];
